app:
  title: C++ Lab (Template Project)
  description: 這是用來測試C++ Lab的模板專案
compiler_path: "g++"
problems:
  p1:
    name: Sum Sum
    points: 25
    timeout: 1
  p2:
    name: Array Operations
    points: 25
    timeout: 1
    cases:
      '01': 10
      '02': 10
      '03': 5
  p3:
    name: String Manipulation
    points: 25
    timeout: 1
  p4:
    name: Basic I/O
    points: 25
    timeout: 1
  p5:
    name: Factorial (Recursion)
    points: 25
    timeout: 1
    forbidden:
    - for
    - while
    - do
    - goto
    required:
    - factorial
  p6:
    name: Factorial Challenge
    points: 25
    timeout: 1
    forbidden:
    - for
    - while
    - do
    - goto
    required:
    - factorial
defaults:
  timeout: 1
